import Head from "next/head";
import React from "react";
import {
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  AreaChart,
  Area,
  ResponsiveContainer,
} from "recharts";
import { api } from "@/utils/api";
import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { dataChartOne } from "@/lib/data";

export default function Home() {
  const { data } = api.post.hello.useQuery();
  const user = useUser();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex flex-col items-end pr-10 pt-5">
          <h3 className="scroll-m-20 text-2xl font-semibold tracking-tight">
            لوحة التحكم
          </h3>
          <p className="leading-7 text-muted-foreground">
            يمكنك العثور على الإحصائيات الخاصة بك هنا
          </p>
        </div>
        <div className="m-10 grid grid-cols-2 gap-10">
          <div className="border bg-white">
            <div className="pr-3 pt-2">
              <h3 className="scroll-m-20 text-end text-xl font-semibold tracking-tight">
                المبيعات
              </h3>
              <p className="text-end leading-7 text-muted-foreground">
                يمكنك رؤية تقدم مبيعاتك من هنا
              </p>
            </div>
            <Chart />
          </div>
          <div className="border bg-white">
            <div className="pr-3 pt-2">
              <h3 className="scroll-m-20 text-end text-xl font-semibold tracking-tight">
                المبيعات
              </h3>
              <p className="text-end leading-7 text-muted-foreground">
                يمكنك رؤية تقدم مبيعاتك من هنا
              </p>
            </div>
            <Chart />
          </div>
          <div className="col-span-2 border bg-white">
            <div className="pr-3 pt-2">
              <h3 className="scroll-m-20 text-end text-xl font-semibold tracking-tight">
                الارباح
              </h3>
              <p className="text-end leading-7 text-muted-foreground">
                يمكنك رؤية تقدم الارباح من هنا
              </p>
            </div>
            <Chart />
          </div>
        </div>
      </main>
    </>
  );
}

export const Chart = ({ className }: { className?: string }) => {
  return (
    <ResponsiveContainer className={className} width="100%" height={200}>
      <AreaChart
        width={500}
        height={200}
        data={dataChartOne}
        syncId="anyId"
        margin={{
          top: 10,
          right: 30,
          left: 0,
          bottom: 0,
        }}
      >
        <CartesianGrid strokeDasharray="3 3" />
        <XAxis dataKey="name" />
        <YAxis />
        <Tooltip />
        <Area type="monotone" dataKey="pv" stroke="#333333" fill="#0E9CFF" />
      </AreaChart>
    </ResponsiveContainer>
  );
};
